image: docker:stable

variables:
  DOCKER_HOST: tcp://localhost:2375
services:
  - docker:dind

stages:
  - build_automation_code
  - run_bdd_test

build_testcafe_chrome_allincluded:
  stage: build_automation_code
  only:
    - master
  tags:
    - kubernetes
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build -t bingc/testcafe_chrome_allincluded:${CI_PIPELINE_ID} -f docker/Dockerfile.testcafe_chrome_allincluded .
  after_script:
    - docker tag bingc/testcafe_chrome_allincluded:${CI_PIPELINE_ID}  bingc/testcafe_chrome_allincluded:latest
    - docker push bingc/testcafe_chrome_allincluded:${CI_PIPELINE_ID}
    - docker push bingc/testcafe_chrome_allincluded:latest
    - docker rmi bingc/testcafe_chrome_allincluded:${CI_PIPELINE_ID}
    - docker rmi bingc/testcafe_chrome_allincluded:latest

run_automation_in_headless_chrome:
  stage: run_bdd_test
  only:
    - master
  tags:
    - kubernetes #bing-linux-local
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull bingc/testcafe_chrome_allincluded:latest
    - docker volume create build-${CI_PIPELINE_ID}
  script:
    - echo "======== Testing ${CI_COMMIT_REF_NAME} ========="
    - docker run --name build-${CI_PIPELINE_ID} --rm -v build-${CI_PIPELINE_ID}:/src/testcafe_bdd/report bingc/testcafe_chrome_allincluded:latest  --world-parameters {\"browser\":\"chrome:headless:no-sandbox\"} -f json:./report/cucumber_report.json
  after_script:
    - echo "======== Aggregating tests ========="
    - docker run --name aggregate-${CI_PIPELINE_ID} -v build-${CI_PIPELINE_ID}:/src/testcafe_bdd/report --entrypoint 'node'  bingc/testcafe_chrome_allincluded:latest --no-warnings ./report_chrome.js
    - docker cp aggregate-${CI_PIPELINE_ID}:/src/testcafe_bdd/report/cucumber_report.html test-results
    - docker rm aggregate-${CI_PIPELINE_ID}
    - docker volume rm build-${CI_PIPELINE_ID}
  artifacts:
    paths:
      - test-results
    when: always
